"""Initial schema

Revision ID: cbd13bb1bae2
Revises: 
Create Date: 2026-05-03 13:41:42.113177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd13bb1bae2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_wallet_address'), 'agent_runs', ['wallet_address'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_run_id'), 'audit_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_wallet_address'), 'audit_logs', ['wallet_address'], unique=False)
    op.create_table('security_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_explanation', sa.Text(), nullable=False),
    sa.Column('approval_recommendation', sa.String(length=32), nullable=False),
    sa.Column('deterministic', sa.Boolean(), nullable=False),
    sa.Column('risk_findings', sa.JSON(), nullable=False),
    sa.Column('policy_findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_evaluations_run_id'), 'security_evaluations', ['run_id'], unique=False)
    op.create_index(op.f('ix_security_evaluations_wallet_address'), 'security_evaluations', ['wallet_address'], unique=False)
    op.create_table('proposed_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('contract_address', sa.String(length=64), nullable=False),
    sa.Column('target_address', sa.String(length=64), nullable=False),
    sa.Column('token_symbol', sa.String(length=12), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('approval_amount_usd', sa.Float(), nullable=False),
    sa.Column('approval_scope', sa.String(length=16), nullable=False),
    sa.Column('approval_expires_in_minutes', sa.Integer(), nullable=False),
    sa.Column('wallet_balance_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['security_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_actions_contract_address'), 'proposed_actions', ['contract_address'], unique=False)
    op.create_index(op.f('ix_proposed_actions_evaluation_id'), 'proposed_actions', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposed_actions_evaluation_id'), table_name='proposed_actions')
    op.drop_index(op.f('ix_proposed_actions_contract_address'), table_name='proposed_actions')
    op.drop_table('proposed_actions')
    op.drop_index(op.f('ix_security_evaluations_wallet_address'), table_name='security_evaluations')
    op.drop_index(op.f('ix_security_evaluations_run_id'), table_name='security_evaluations')
    op.drop_table('security_evaluations')
    op.drop_index(op.f('ix_audit_logs_wallet_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_run_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_wallet_address'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
